#!/usr/bin/env php
<?php

echo "Reactive Application Build Tool v1.0\n\n";

// get app information
$app = json_decode(file_get_contents("app.json"), true);

// set display name
echo "Set display name: {$app['displayName']}\n";

$file = "android/app/src/main/res/values/strings.xml";
echo "   in $file\n";
$content = preg_replace('/(<string name="app_name">)([\w|\s]*)(<\/string>)/', "\\1{$app['displayName']}\\3", file_get_contents($file));
file_put_contents($file, $content);

$file = "ios/reactive/Info.plist";
echo "   in $file\n";
$content = preg_replace('/(<key>CFBundleDisplayName<\/key>(\s*)<string>)([\w|\s]*)(<\/string>)/', "\\1{$app['displayName']}\\4", file_get_contents($file));
file_put_contents($file, $content);

// set version
echo "Set version: {$app['version']}\n";

$file = "android/app/build.gradle";
echo "   in $file\n";
$content = preg_replace('/versionName "([\d|\.]+)"/', "versionName \"{$app['version']}\"", file_get_contents($file));
file_put_contents($file, $content);

$file = "ios/reactive/Info.plist";
echo "   in $file\n";
$content = preg_replace('/(<key>CFBundleShortVersionString<\/key>(\s*)<string>)([\d|\.]*)(<\/string>)/', "\\1 {$app['version']}\\4", file_get_contents($file));
file_put_contents($file, $content);

// submit git
$status = exec("git status");
if ("nothing to commit, working tree clean" != $status) {
    echo "Submit git\n";
    exec("git add .");
    echo "   commit message: ";
    $answer = trim(fgets(STDIN));
    if (!$answer) {
        echo "\n  Quit submit.\n";
        exit(0);
    }
    exec("git commit -m '{$answer}'");
}

// set git short version to build
$build = exec("git rev-parse --short HEAD");
$file = "app.json";
$content = preg_replace('/("build": )"(\s*)"/', "\\1\"{$build}\"", file_get_contents($file));
file_put_contents($file, $content);

// package Android
echo "Whether to package Android?  [Yes|No] ";
$answer = trim(fgets(STDIN));
if (strncasecmp($answer, 'y', 1)) {
    exit(0);
}

$file = "market.json";
echo "   Set the market name, multiple divided by \",\" [official] ";
$answer = trim(fgets(STDIN));
$market = $answer ? explode(",", $answer) : ["official"];
echo "   Start packing...\n";
foreach ($market as $value) {
    file_put_contents("market.json", json_encode(["name" => $value]));
    system("cd android && ./gradlew assembleRelease");
    exec("cd android/app/build/outputs/apk && mv app-release* app-market-{$value}-.apk");
}
system("ls android/app/build/outputs/apk");